version: '3.4'

services:
    api:
        build:
            context: .
            target: development
            args:
                NODE_ENV: development
        volumes:
            - ./src:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 5001:5000
        environment:
            - NODE_ENV=development
            - MONGO_USER=tuancao
            - MONGO_PASSWORD=26072002
            - SESSION_SECRET=secret
        command: bun run dev

    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=tuancao
            - MONGO_INITDB_ROOT_PASSWORD=26072002
