version: '25.0.2'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: maple-metting-docker-server:latest
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=5000
      - VERSION=v1
    ports:
      - "80:3000"
    volumes:
      - /app/node_modules
      - ./src:/usr/src/app
