version: '3.4'

services:
    bun-app:
        container_name: discord-dev-container
        build:
            context: .
            target: development
            args:
                NODE_ENV: development
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 5000:5000
        env_file:
            - ./.env.development
        command: bun run dev
