version: '3.4'

services:
    api:
        build:
            context: .
            target: development
        volumes:
            - ./src:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 5001:5000
        command: bun run dev
