version: '3.4'

services:
    bun-app:
        container_name: discord-prod-container
        build:
            context: .
            target: production
            args:
                NODE_ENV: production
        ports:
            - 5001:5000
        env_file:
            - ./.env
        # command: >
        #     bash -c "bun run start"
