services:
  - name: nodejs
    buildCommand: docker-compose build
    startCommand: docker-compose up -d
    env: .env
    envVars:
      - key: PORT
        from: env
      - key: VERSION
        from: env
    healthCheckPath: /
    plan: starter
    ports:
      - 80:8080
    volumes:
      - /app/node_modules
      - ./src:/usr/src/app