version: 1
services:
    - type: web
      name: bun-app
      env: .env
      startCommand: bash -c "bun run start"
      buildCommand: docker build -t discord-prod-container --target production --build-arg NODE_ENV=production .
      healthCheckPath: /
      envVars:
          - key: NODE_ENV
            from: env
          - key: PORT
            from: env
      ports:
          - 5001:5000
      volumes:
          - localPath: ./
            renderPath: /usr/src/app
          - localPath: /usr/src/app/node_modules
            renderPath: /usr/src/app/node_modules
